var canvas = document.getElementById("canvas");
var canvasc = canvas.getContext("2d");
var canvasWidth = 600;
var canvasHeight = 600;
canvas.width = canvasWidth;
canvas.height = canvasHeight;
canvasc.fillStyle = "grey"
canvasc.fillRect(0, 0, 300,300);
canvasc.fillStyle = "red";
canvasc.beginPath();
canvasc.arc(150, 150, 125, 0, 10 * Math.PI);
canvasc.closePath();
canvasc.fill();
canvasc.fillStyle = "yellow";
canvasc.beginPath();
canvasc.arc(150, 150, 100, 0, 10 * Math.PI);
canvasc.closePath();
canvasc.fill();
canvasc.fillStyle = "green";
canvasc.beginPath();
canvasc.arc(150, 150, 75, 0, 10 * Math.PI);
canvasc.closePath();
canvasc.fill();
canvasc.fillStyle = "white";
canvasc.beginPath();
canvasc.arc(150, 150, 50, 0, 10 * Math.PI);
canvasc.closePath();
canvasc.fill();
canvasc.fillStyle = "red";
canvasc.beginPath();
canvasc.arc(150, 150, 25, 0, 10 * Math.PI);
canvasc.closePath();
canvasc.fill(); 